eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #espera de lectura del servicio
      routes:
        - id: clientes
          uri: http:/localhost:8090
          predicates:
            -path=/api/v1/** #ruta de acceso a la api