eureka:
  client:
    register-with-eureka: false

server:
  port: 8080 #microservicio de peticones por defaul

spring:
  config: #configuracion del server
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        location:
          locator:
            enabled: true  #microservicio activo y esprando
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/** #el ** define que puede acceder a cualquier ruta o destino del microservicio
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/courses/**

